### ISSUE TITLE
No longer detects updates correctly

### ISSUE THREAD

**Issue by PlusJack** [CallMeAldy/AK-Kernel-Updater#3]
Worked perfectly up until recently (~AK version 140)
Now when it checks for updates, it will always say there's an update even if you already have the latest version.

![image](https://cloud.githubusercontent.com/assets/6070672/7217588/33fa348c-e5f9-11e4-827c-7b3701ad5358.png)

If you try to get it, it says the one already on your devices matches the MD5. So this confirms that it's the exact same file.

![image](https://cloud.githubusercontent.com/assets/6070672/7217590/7f0cf64e-e5f9-11e4-92aa-1e2974139273.png)

**Comment by themike10452** [comment]
this is Aldrin's fault. As you can see there's a difference in names, .OPO is missing from the package name on the app so it thinks it's a different kernel version. can be easily fixed from our side don't worry. I'll fix it now, thanks for mentioning it :)

**Comment by themike10452** [comment]
sorry that's for OPO so it's anarkia fault :P

**Comment by themike10452** [comment]
fixed :)

**Comment by Conn2005** [comment]
I'm having an issue. App says only version 269 available but 270 is available from AK website. 
![screenshot_2015-06-28-14-10-19](https://cloud.githubusercontent.com/assets/13089731/8397880/56c53ee2-1da0-11e5-9250-4f65f60c5498.png)

**Comment by themike10452** [comment]
it's not an issue related to the app's logic, Aldrin didn't push the update to the app.
