### ISSUE TITLE
Not on Google Play Store Anymore

### ISSUE THREAD

**Issue by Maxqia** [CallMeAldy/AK-Kernel-Updater#4]
https://play.google.com/store/apps/details?id=com.aldrinholmes.akupdater&rdid=com.aldrinholmes.akupdater&rdot=1&feature=md 
Returns Not Found

**Comment by aldrinholmes** [comment]
https://plus.google.com/+AldrinHolmes20/posts/FA3XPWjnR8K

Updates will be provided on my Google+
