### ISSUE TITLE
No download 

### ISSUE THREAD

**Issue by Tjaksch** [CallMeAldy/AK-Kernel-Updater#7]
Hi there. I got a issue... 
No download is possible.  I set the proxy, I've freshly installed ak updater, but even the same error... 
Please help! 
Thx from Germany! 
Timo

![screenshot_2015-07-29-16-40-04](https://cloud.githubusercontent.com/assets/13557185/8960614/137366a8-3611-11e5-9139-ebd64bdf9a19.png)

**Comment by aldrinholmes** [comment]
Is this version 1.2 from my Github?

**Comment by Tjaksch** [comment]
No 1.0...
Where did I find the new one?

**Comment by aldrinholmes** [comment]
Click on Releases tab above and download it

**Comment by Tjaksch** [comment]
Thank you very much

**Comment by aldrinholmes** [comment]
Welcome :)
